from datetime import date

from api.app.models import Equipment, EquipmentStatus


EQUIPMENT_RECORDS = [
    Equipment(
        equipment_id="FF-BC-1007",
        model="BC-150 Brush Chipper",
        category="Tree Care",
        serial_number="BC150-2026-1842",
        location="Des Moines, Iowa",
        assigned_dealer="Central Equipment Services",
        status=EquipmentStatus.OPERATIONAL,
        engine_hours=1287.4,
        fuel_level=64.0,
        health_score=96,
        last_service_date=date(2026, 8, 14),
    ),
    Equipment(
        equipment_id="FF-DD-2041",
        model="DD-40 Directional Drill",
        category="Underground Construction",
        serial_number="DD40-2025-0917",
        location="Denver, Colorado",
        assigned_dealer="Front Range Equipment",
        status=EquipmentStatus.WARNING,
        engine_hours=2104.8,
        fuel_level=51.0,
        health_score=78,
        last_service_date=date(2026, 7, 29),
    ),
    Equipment(
        equipment_id="FF-TR-3018",
        model="TR-95 Trencher",
        category="Utility Installation",
        serial_number="TR95-2024-2271",
        location="Omaha, Nebraska",
        assigned_dealer="Heartland Machine Group",
        status=EquipmentStatus.CRITICAL,
        engine_hours=3420.2,
        fuel_level=38.0,
        health_score=52,
        last_service_date=date(2026, 6, 18),
    ),
    Equipment(
        equipment_id="FF-RC-4025",
        model="RC-60 Recycling System",
        category="Environmental",
        serial_number="RC60-2026-0445",
        location="Austin, Texas",
        assigned_dealer="Lone Star Industrial",
        status=EquipmentStatus.MAINTENANCE,
        engine_hours=876.9,
        fuel_level=72.0,
        health_score=85,
        last_service_date=date(2026, 8, 25),
    ),
    Equipment(
        equipment_id="FF-SG-5032",
        model="SG-80 Stump Grinder",
        category="Tree Care",
        serial_number="SG80-2025-1388",
        location="Kansas City, Missouri",
        assigned_dealer="Midwest Equipment Partners",
        status=EquipmentStatus.OFFLINE,
        engine_hours=1689.6,
        fuel_level=29.0,
        health_score=61,
        last_service_date=date(2026, 7, 11),
    ),
]